# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_phone', models.CharField(max_length=20)),
                ('truck_registration', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_type', models.CharField(choices=[('OUTGOING', 'Outgoing'), ('RETURN', 'Return')], max_length=50)),
                ('inspection_notes', models.TextField(blank=True)),
                ('is_safe_for_transport', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('signed_by_driver', models.BooleanField(default=False)),
                ('signed_by_scaffolder', models.BooleanField(default=False)),
                ('signed_by_security', models.BooleanField(default=False)),
                ('signed_by_client', models.BooleanField(default=False)),
                ('driver_signature_date', models.DateTimeField(blank=True, null=True)),
                ('scaffolder_signature_date', models.DateTimeField(blank=True, null=True)),
                ('security_signature_date', models.DateTimeField(blank=True, null=True)),
                ('client_signature_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='delivery_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Note',
                'verbose_name_plural': 'Delivery Notes',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Delivery Note Item',
                'verbose_name_plural': 'Delivery Note Items',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grv_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('issued_by_client', models.BooleanField(default=False)),
                ('all_items_received', models.BooleanField(default=False)),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='grv_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Goods Received Voucher',
                'verbose_name_plural': 'Goods Received Vouchers',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='GRVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('condition_on_receipt', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'GRV Item',
                'verbose_name_plural': 'GRV Items',
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateField()),
                ('truck_type_required', models.CharField(choices=[('SMALL', 'Small Truck (5-10 tons)'), ('MEDIUM', 'Medium Truck (10-20 tons)'), ('LARGE', 'Large Truck (20-30 tons)'), ('FLATBED', 'Flatbed Truck'), ('CRANE', 'Crane Truck')], max_length=100)),
                ('delivery_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport Request',
                'verbose_name_plural': 'Transport Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
