# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='hire_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.hireorder'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grvitem',
            name='grv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.goodsreceivedvoucher'),
        ),
        migrations.AddField(
            model_name='grvitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
        migrations.AddField(
            model_name='goodsreceivedvoucher',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='goodsreceivedvoucher',
            name='hire_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.hireorder'),
        ),
        migrations.AddField(
            model_name='goodsreceivedvoucher',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grvs_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='hire_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.hireorder'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_inspected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='transport_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.transportrequest'),
        ),
    ]
