# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_initial'),
        ('finance', '0001_initial'),
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='hire_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiring.hireorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hire_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiring.hireorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='revenuerecord',
            unique_together={('hire_order', 'period_start', 'period_end')},
        ),
    ]
