# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('storage_location', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Archived Document',
                'verbose_name_plural': 'Archived Documents',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('SIGNED', 'Signed'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('UPDATED', 'Updated')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Log',
                'verbose_name_plural': 'Document Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Fossil Contracting', max_length=200)),
                ('company_address', models.TextField(default='123 Industrial Area, Harare, Zimbabwe')),
                ('company_phone', models.CharField(default='+263 242 123456', max_length=50)),
                ('company_email', models.EmailField(default='info@fossilcontracting.co.zw', max_length=254)),
                ('company_website', models.URLField(default='https://www.fossilcontracting.co.zw')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('vat_number', models.CharField(default='VAT123456789', max_length=50)),
                ('tin_number', models.CharField(default='TIN987654321', max_length=50)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('quotation_validity_days', models.IntegerField(default=30)),
                ('invoice_due_days', models.IntegerField(default=30)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('footer_text', models.TextField(default='Thank you for your business!')),
                ('terms_and_conditions', models.TextField(default='Standard terms and conditions apply.')),
                ('send_document_emails', models.BooleanField(default=True)),
                ('email_subject_prefix', models.CharField(default='[Fossil Contracting]', max_length=100)),
                ('email_signature', models.TextField(default='Best regards,\nThe Fossil Contracting Team')),
                ('auto_archive_days', models.IntegerField(default=730, help_text='Documents older than this will be archived (2 years)')),
                ('auto_delete_days', models.IntegerField(default=1095, help_text='Documents older than this will be deleted (3 years)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Setting',
                'verbose_name_plural': 'Document Settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('DELIVERY_NOTE', 'Delivery Note'), ('GOODS_RECEIVED_VOUCHER', 'Goods Received Voucher'), ('REQUEST_FOR_QUOTATION', 'Request for Quotation'), ('RECEIPT', 'Receipt')], max_length=50)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='document_templates/')),
                ('html_template', models.TextField(blank=True, help_text='HTML template with variables like {{client.name}}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('DELIVERY_NOTE', 'Delivery Note'), ('GOODS_RECEIVED_VOUCHER', 'Goods Received Voucher'), ('REQUEST_FOR_QUOTATION', 'Request for Quotation'), ('RECEIPT', 'Receipt')], max_length=50)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='generated_documents/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='pdf', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverynote')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
                ('goods_received_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.goodsreceivedvoucher')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-generated_at'],
            },
        ),
    ]
