# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiring', '0001_initial'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='lease_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring.leaseagreement'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring.quotation'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='request_for_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiring.requestforquotation'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate'),
        ),
        migrations.AddField(
            model_name='documentsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.generateddocument'),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiveddocument',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiveddocument',
            name='original_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.generateddocument'),
        ),
    ]
