# Generated by Django 4.2 on 2026-01-02 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blacklist Reason',
                'verbose_name_plural': 'Blacklist Reasons',
                'ordering': ['severity', 'reason_code'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('trading_as', models.CharField(blank=True, help_text='Trading name if different', max_length=200)),
                ('client_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('GOVERNMENT', 'Government'), ('PRIVATE', 'Private'), ('INDIVIDUAL', 'Individual')], default='EXTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('contact_person', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Zimbabwe phone number format: +263 xxx xxx xxx', max_length=128, region='ZW')),
                ('alternate_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ZW')),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('physical_address', models.TextField()),
                ('postal_address', models.TextField(blank=True)),
                ('city', models.CharField(default='Harare', max_length=100)),
                ('province', models.CharField(default='Harare', max_length=100)),
                ('country', django_countries.fields.CountryField(default='ZW', max_length=2)),
                ('gps_coordinates', models.CharField(blank=True, help_text='GPS coordinates (optional)', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='Tax Identification Number (TIN)', max_length=100)),
                ('vat_number', models.CharField(blank=True, help_text='VAT Registration Number', max_length=100)),
                ('business_sector', models.CharField(blank=True, max_length=200)),
                ('year_established', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_rating', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(choices=[('IMMEDIATE', 'Immediate Payment'), ('7_DAYS', '7 Days'), ('14_DAYS', '14 Days'), ('30_DAYS', '30 Days'), ('60_DAYS', '60 Days'), ('90_DAYS', '90 Days')], default='30_DAYS', max_length=20)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('relationship_start_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('client_contract', models.FileField(blank=True, null=True, upload_to='client_contracts/')),
                ('kyc_document', models.FileField(blank=True, help_text='Know Your Customer document', null=True, upload_to='client_kyc/')),
                ('certificate_of_registration', models.FileField(blank=True, null=True, upload_to='client_registrations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='blacklist_evidence/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client Blacklist',
                'verbose_name_plural': 'Client Blacklist',
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary Contact'), ('SECONDARY', 'Secondary Contact'), ('ACCOUNTS', 'Accounts Department'), ('TECHNICAL', 'Technical Contact'), ('PROCUREMENT', 'Procurement'), ('SITE_MANAGER', 'Site Manager')], default='SECONDARY', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ZW')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ZW')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'ordering': ['client', 'contact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('KYC', 'KYC Document'), ('CERTIFICATE', 'Certificate of Registration'), ('TAX_CLEARANCE', 'Tax Clearance Certificate'), ('BANK_DETAILS', 'Bank Details'), ('ID', 'ID Document'), ('INSURANCE', 'Insurance Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='client_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGE', 'Status Changed'), ('CREDIT_LIMIT_CHANGE', 'Credit Limit Changed'), ('BALANCE_UPDATE', 'Balance Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('NOTE_ADDED', 'Note Added'), ('CONTACT_ADDED', 'Contact Added'), ('SITE_ADDED', 'Site Added')], max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client History',
                'verbose_name_plural': 'Client History',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', 'General Note'), ('MEETING', 'Meeting Notes'), ('PHONE_CALL', 'Phone Call'), ('EMAIL', 'Email'), ('VISIT', 'Site Visit'), ('COMPLAINT', 'Complaint'), ('FOLLOW_UP', 'Follow Up'), ('CREDIT_REVIEW', 'Credit Review')], default='GENERAL', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_timeliness', models.IntegerField(help_text='1=Very Poor, 5=Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cooperation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('volume_of_business', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('profitability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Rating',
                'verbose_name_plural': 'Client Ratings',
                'ordering': ['-rating_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('site_manager', models.CharField(blank=True, max_length=200)),
                ('site_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='ZW')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main_site', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Site',
                'verbose_name_plural': 'Client Sites',
                'ordering': ['client', 'site_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-issued_date'],
            },
        ),
    ]
